#!/usr/bin/env bash
# =============================================================================
# WeberQ ERP — Docker Entrypoint
# Generates /etc/odoo/odoo.conf from environment variables at startup.
#
# Environment variables:
#   HOST        - PostgreSQL host        (default: db)
#   PORT        - PostgreSQL port        (default: 5432)
#   USER        - PostgreSQL user        (default: odoo)
#   PASSWORD    - PostgreSQL password    (required)
#   WORKERS     - Odoo worker processes  (default: 4)
#   LOG_LEVEL   - Odoo log level        (default: info)
#   ADMIN_PASSWD- Odoo master password  (default: changeme)
# =============================================================================

set -e

DB_HOST="${HOST:-db}"
DB_PORT="${PORT:-5432}"
DB_USER="${USER:-odoo}"
DB_PASSWORD="${PASSWORD:-}"
WORKERS="${WORKERS:-4}"
LOG_LEVEL="${LOG_LEVEL:-info}"
ADMIN_PASSWD="${ADMIN_PASSWD:-changeme}"

# ─── Generate odoo.conf ──────────────────────────────────────────────────────
cat > /etc/odoo/odoo.conf << EOF
[options]
; WeberQ ERP — auto-generated by docker-entrypoint.sh

; Addons paths
addons_path = /opt/odoo/addons,/opt/odoo/custom_addons

; Data directory (filestore, sessions)
data_dir = /var/lib/odoo

; Database
db_host = ${DB_HOST}
db_port = ${DB_PORT}
db_user = ${DB_USER}
db_password = ${DB_PASSWORD}

; Master password (for DB management UI)
admin_passwd = ${ADMIN_PASSWD}

; Network
http_port = 8069
longpolling_port = 8072
proxy_mode = True

; Workers (set 0 for dev single-thread mode)
workers = ${WORKERS}
max_cron_threads = 2

; Logging
logfile = False
log_level = ${LOG_LEVEL}
log_handler = :INFO

; Limits
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
EOF

echo "[entrypoint] odoo.conf written. Starting Odoo..."

exec python3 /opt/odoo/odoo-bin "$@"
